package:
  name: python-multipart
  version: 0.0.20
  top-level:
    - multipart
    - python_multipart
source:
  url: https://files.pythonhosted.org/packages/45/58/38b5afbc1a800eeea951b9285d3912613f2603bdf897a4ab0f4bd7f405fc/python_multipart-0.0.20-py3-none-any.whl
  sha256: 8a62d3a8335e06589fe01f2a3e178cdcc632f3fbe0d492ad9ee0ec35aab1f104
about:
  home: null
  PyPI: https://pypi.org/project/python-multipart
  summary: A streaming multipart parser for Python
  license: null
extra:
  recipe-maintainers:
    - PUT_YOUR_GITHUB_USERNAME_HERE
