package:
  name: openai
  version: 1.84.0
  top-level:
    - openai
source:
  url: https://files.pythonhosted.org/packages/py3/o/openai/openai-1.84.0-py3-none-any.whl
  sha256: 7ec4436c3c933d68dc0f5a0cef0cb3dbc0864a54d62bddaf2ed5f3d521844711
requirements:
  run:
    - httpx
    - pydantic
    - typing-extensions
    - distro
    - anyio
    - sniffio
about:
  home: ""
  PyPI: https://pypi.org/project/openai
  summary: The official Python library for the openai API
  license: ""
extra:
  recipe-maintainers:
    - hoodmane
