package:
  name: urllib3
  version: 2.3.0
  top-level:
    - urllib3
source:
  url: https://files.pythonhosted.org/packages/source/u/urllib3/urllib3-2.3.0.tar.gz
  sha256: f8c5449b3cf0861679ce7e0503c7b44b5ec981bec0d1d3795a07f1ba96f0204d
test:
  imports:
    - urllib3
    - urllib3.contrib.emscripten
about:
  home: https://github.com/urllib3/urllib3
  PyPI: https://pypi.org/project/urllib3
  summary: HTTP library with thread-safe connection pooling, file post, and more.
  license: MIT
