package:
  name: distro
  version: 1.9.0
  top-level:
    - distro
source:
  url: https://files.pythonhosted.org/packages/12/b3/231ffd4ab1fc9d679809f356cebee130ac7daa00d6d6f3206dd4fd137e9e/distro-1.9.0-py3-none-any.whl
  sha256: 7bffd925d65168f85027d8da9af6bddab658135b840670a223589bc0c8ef02b2
about:
  home: https://github.com/python-distro/distro
  PyPI: https://pypi.org/project/distro
  summary: Distro - an OS platform information API
  license: Apache License, Version 2.0
extra:
  recipe-maintainers:
    - PUT_YOUR_GITHUB_USERNAME_HERE
